### PR TITLE
fix: source mapping original path instead of user-provided input

### LINKED ISSUE #963: Breakpoint is set to a wrong line when the user-provided breakpoint path is a partial path
#### Background

This is a bug discovered during the investigation for #932. When the user-provided breakpoint request has the path that is not a full relative path to the root directory of the application, (for example `index.ts` instead of `src/index.ts`), the breakpoint will be set to a wrong line (line 0) because the relative path of the target file to the source map is wrongly generated.

#### Environment details

  - OS: Debian 5.10.26
  - Node.js version: v12.21.0
  - npm version: 7.5.2
  - `@google-cloud/debug-agent` version: 5.2.0

### PR DESCRIPTION
**Pull request by Louis-Ye**
Uses the original source path in the mapInfo instead of user-provided input to check the generated sources, so that when the user provided a partial match of the file, we can still correctly map the original file to the generated file.

This PR is based on PR #977 

Fixes #963

### CODE REVIEW

File: src/agent/io/sourcemapper.ts [hunk 1]
```diff
@@ -167,17 +174,10 @@ async function processSourcemap(
...
-  /**
-   * @param {Array.<string>} sourcemapPaths An array of paths to .map sourcemap
-   *  files that should be processed.  The paths should be relative to the
-   *  current process's current working directory
-   * @param {Logger} logger A logger that reports errors that occurred while
-   *  processing the given sourcemap files
-   * @constructor
-   */
-  constructor() {
+  constructor(readonly logger: Logger) {
```
Comment (mctavish) [inline src/agent/io/sourcemapper.ts:180]: Private constructor?

File: src/agent/io/sourcemapper.ts [hunk 2]
```diff
@@ -34,6 +35,10 @@ export interface MapInfoInput {
   // process's working directory).
   outputFile: string;
 
+  // The path of the original source file. In the example above, this will be
```
Comment (mctavish) [inline src/agent/io/sourcemapper.ts:38]: Please specify what this path is relative to.

File: test/test-sourcemapper.ts [hunk 3]
```diff
@@ -234,11 +267,19 @@ testTool(
   ]
 );
 
+testTool(
```
Comment (mctavish) [inline test/test-sourcemapper.ts:270]: Is this the test that repros the original issue?  If so, please add some additional description or pointer to the bug because I'm a bit too dense to figure out what this is verifying.

**Review by JustinBeckwith — APPROVED** [review]
LGTM from a TypeScript perspective

File: test/test-sourcemapper.ts (hunk 3 above)
Comment (Louis-Ye) [reply test/test-sourcemapper.ts:320]: Added the comments.

File: src/agent/io/sourcemapper.ts (hunk 2 above)
Comment (Louis-Ye) [reply src/agent/io/sourcemapper.ts]: Done.

File: src/agent/io/sourcemapper.ts (hunk 1 above)
Comment (Louis-Ye) [reply src/agent/io/sourcemapper.ts]: The create() function is actually not a static function of this class, marking the constructor as private will change the usage of this function in all places. I think for this PR, it is better to keep it as it is, what do you think?

File: src/agent/io/sourcemapper.ts [hunk 4]
```diff
@@ -218,13 +225,12 @@ export class SourceMapper {
...
 
   /**
-   * @param {string} inputPath The path to an input file that could possibly
-   *  be the input to a transpilation process.  The path should be relative to
-   *  the process's current working directory
    * @param {number} The line number in the input file where the line number is
    *   zero-based.
    * @param {number} (Optional) The column number in the line of the file
    *   specified where the column number is zero-based.
+   * @param {string} The entry of the source map info in this.infoMap.
```
Comment (mctavish) [inline src/agent/io/sourcemapper.ts:232]: Please update this comment; the type isn't a string, and I'm not able to understand what this parameter should be based on this documentation.

**Review by mctavish — APPROVED** [review]
One small change to make, but looks good.

File: src/agent/io/sourcemapper.ts (hunk 4 above)
Comment (Louis-Ye) [reply src/agent/io/sourcemapper.ts]: Done.
